### ISSUE TITLE
Sorting does not work on column STATE in postgresql 10

### ISSUE THREAD

**Issue by AlexanderKkK** [technology16/pgsqlblocks#18]
I use pgSqlBlocks-1.4.0-Windows-64.jar
Sorting does not work on column STATE in postgresql 10. Оn postgresql 9.6 is working.
Sometime I get an error:
An error has occurred. See error log for more details.
java.lang.NullPointerException

**Comment by antoon-r** [comment]
Fixed in #22

**Comment by antoon-r** [comment]
Due to unknown reasons, the `state` column in `pg_stat_activity` now sometimes contains **null**. Documentation for this column is same for 9.6 and 10.0.
