### ISSUE TITLE
Мешает авто прокрутка строк таблицы при автоматическом обновлении блокировок

### ISSUE THREAD

**Issue by volodin-aa** [technology16/pgsqlblocks#30]
Если включено авто обновление обновление блокировок и выделена строка, то если прокрутить таблицу далее для просмотра текущих запросов, то после обновления информации таблица прокрутится назад до выделенной строки.

Не удобно при большом количестве выполняемых запросов..

**Comment by AXEPOH** [comment]
Исправлено в #48
