### ISSUE TITLE
Обрезается текст запроса

### ISSUE THREAD

**Issue by volodin-aa** [technology16/pgsqlblocks#31]
![8c6d1385](https://user-images.githubusercontent.com/5697239/45075016-589a1c80-b0ee-11e8-8ee3-c7f55de5c413.png)

**Comment by Nataly-Sagel** [comment]
Текст запроса хранится в stat_activity. По умолчанию длина запроса 1024 символа
https://postgrespro.ru/docs/postgrespro/10/monitoring-stats#MONITORING-STATS-VIEWS
