### ISSUE TITLE
Блокирующий запрос отображается не полностью

### ISSUE THREAD

**Issue by makeconfig2017** [technology16/pgsqlblocks#39]
Здравствуйте,
Почему-то блокирующий запрос отобразился не полностью, впервые заметил сегодня, до этого все запросы отображались нормально, запрос COPY
![Screenshot_20190918_143316](https://user-images.githubusercontent.com/26453996/65145964-75687000-da23-11e9-8747-cb87bfddb3d3.png)

**Comment by makeconfig2017** [comment]
Need to set 'track_activity_query_size' https://www.postgresql.org/docs/10/runtime-config-statistics.html

**Comment by antoon-r** [comment]
Да, это в настройках сервера делается
