### ISSUE TITLE
Сортировка по названию и кол-ву процессов в окне баз данных

### ISSUE THREAD

**Issue by makeconfig2017** [technology16/pgsqlblocks#50]
Просьба если есть возможность, добавить сортировку по названию БД и кол-ву процессов в окне названий БД. И если можно, возможность переставлять их (строки названий БД) в произвольном порядке, возможно если будет ещё возможность, добавить группы.

**Comment by Endeavourl** [comment]
сделали в #51 
перестановку делать не стали, непонятно как она должна взаимодействовать с сортировкой
группы можно сделать назвав подключения с префиксами
